---
title: "NetLogoLayerPrep"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r libraries}
rm(list=ls())
library(raster)
library(sf)

```

```{r data}

# NetLogo friendly projection
new_crs <- "+proj=aea +lat_1=20 +lat_2=60 +lat_0=40 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"

# Read in polygons that we'll use to crop rasters to focal pinchpoints and reproject
# pp1_shp <- read_sf("../Circuitscape/pinchpointcroppolys/pinchpoint1.shp") %>% 
#   st_transform(new_crs)

pp3_shp <- read_sf("../Circuitscape/pinchpointcroppolys/pinchpoint3.shp") %>% 
  st_transform(new_crs)

# Read in rasters
corridors <- raster("../Circuitscape/pinchpointoutput/addI70_corridors_truncated_at_10k1.tif")
pinchpoints <- raster("../Circuitscape/pinchpointoutput/addI70_current_adjacentPairs_10k1.tif")
resistance <- raster("../Circuitscape/circuitscapeInput/resistance.tif")

# Reproject rasters to new crs
corridors_rpj <- projectRaster(from = corridors,crs=new_crs)
pinchpoints_rpj <- projectRaster(from = pinchpoints,crs=new_crs)
resistance_rpj <- projectRaster(from=resistance,crs=new_crs)

# Put rasters in a list to make for loop easy
raster_list <- list(corridors=corridors_rpj,
                    pinchpoints=pinchpoints_rpj,
                    resistance=resistance_rpj)

# Create blank raster template to resample rasters to higher resoluion (90m to 30m)
ras <- raster()
extent(ras) <- extent(pinchpoints_rpj)
res(ras) <- 30
crs(ras)<-new_crs

for(i in 1:length(raster_list)){
  
  rasi <- raster_list[[i]]
  tmp <- crop(rasi,extent(ras)) %>% resample(.,ras)
  assign(paste0(names(raster_list[i]),"_resample"),tmp)
  rm(tmp,rasi)
  
}

rm(ras,corridors,corridors_rpj,pinchpoints,pinchpoints_rpj,resistance,resistance_rpj)
```


```{r fill.raster.na}
fill.na <- function(x, i=5) {
  if(is.na(x)[i]) {
    return(round(mean(x, na.rm=TRUE),6))
  } else {
    return(round(x[i],6))
  }
}
```


```{r pinchpoint1}
# Create list of rasters
raster_list2 <- list(corridors=corridors_resample,
                    pinchpoints=pinchpoints_resample,
                    resistance=resistance_resample)

# Create list of pinchpoints
pinchpoint_list  <- list(pp3=pp3_shp)

# Pinchpoint loop
for(i in 1:length(pinchpoint_list)) {
  
  pp_name <- names(pinchpoint_list[i])
  tmp_pp <- pinchpoint_list[[i]]
  
  # Raster loop
  for(j in 1:length(raster_list2)){
    
    ras_name <- names(raster_list2[j])
    tmp_ras <- raster_list2[[j]]

    tmp_mask <- mask(crop(tmp_ras,extent(tmp_pp)),tmp_pp)
    
    # Fill in NA values for resistance and pinchpoint rasters
    if(ras_name != "corridors"){
      while(sum(is.na(tmp_mask[]))>0){
        tmp_mask <- focal(tmp_mask, w = matrix(1,3,3), fun = fill.na, 
              pad = TRUE, na.rm = FALSE )
      }
    }
    assign(paste0(pp_name,"_",ras_name),tmp_mask)
    
    output_tif <- paste0("../GoatRepo/NetLogoInput/",pp_name,"_",ras_name,"_30.tif")
    output_asc <- paste0("../GoatRepo/NetLogoInput/",pp_name,"_",ras_name,"_30.asc")
    writeRaster(tmp_mask,output_tif,overwrite=T)
    writeRaster(tmp_mask,output_asc,overwrite=T,format='ascii')

    }
  
  rm(pp_name,tmp_pp,ras_name,tmp_ras,tmp_mask,output_asc,output_tif)
}


```

# Multiply flow/pinchpoint values by 1000 to help with NetLogo value recognition
```{r fixFlowVals}

# pp1_asc <- raster("./NetLogoInput/pp1_pinchpoints.asc")
# pp1 <- round(pp1_asc*1000,2)
# writeRaster(pp1,"./NetLogoInput/pp1_flow.asc",format="ascii",overwrite=T)
# 
# pp2_asc <- raster("./NetLogoInput/pp2_pinchpoints.asc")
# pp2 <- round(pp2_asc*1000,2)
# writeRaster(pp2,"./NetLogoInput/pp2_flow.asc",format="ascii",overwrite=T)

pp3_30_asc <- raster("./NetLogoInput/pp3_pinchpoints_30.asc")
pp3_30 <- round(pp3_30_asc*1000,2)
writeRaster(pp3_30,"./NetLogoInput/pp3_30_flow.asc",format="ascii",overwrite=T)

pp3_60_asc <- raster("./NetLogoInput/pp3_pinchpoints_60.asc")
pp3_60 <- round(pp3_60_asc*1000,2)
writeRaster(pp3_60,"./NetLogoInput/pp3_60_flow.asc",format="ascii",overwrite=T)

pp3_90_asc <- raster("./NetLogoInput/pp3_pinchpoints_90.asc")
pp3_90 <- round(pp3_90_asc*1000,2)
writeRaster(pp3_90,"./NetLogoInput/pp3_90_flow.asc",format="ascii",overwrite=T)
dim(pp3_90)
```


# Remove river from PP1
```{r removepp1river}

pp1res <- raster("./NetLogoInput/pp1_resistance.asc")
plot(pp1res)
hist(pp1res)

pp1freq <- as.data.frame(freq(pp1res))

pp1reclass <- reclassify(pp1res,
                         rcl = c(50,600,20))

writeRaster(pp1reclass,"./NetLogoInput/pp1_resistance_noriver.asc",format="ascii")
```



